export const ERROR_CODES = {
  SETUP_REQUIRED: "SETUP_REQUIRED",
  API_KEY_MISSING: "API_KEY_MISSING",
  INVALID_PROVIDER_SETTINGS: "INVALID_PROVIDER_SETTINGS",
  PROVIDER_AUTH_FAILED: "PROVIDER_AUTH_FAILED",
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  PROVIDER_BAD_RESPONSE: "PROVIDER_BAD_RESPONSE",
  DOCUMENT_EMPTY: "DOCUMENT_EMPTY",
  DOCUMENT_TOO_SMALL: "DOCUMENT_TOO_SMALL",
  DOCUMENT_TOO_LARGE: "DOCUMENT_TOO_LARGE",
  EXTRACTION_FAILED: "EXTRACTION_FAILED",
  SCAN_ALREADY_RUNNING: "SCAN_ALREADY_RUNNING",
  SCAN_CANCELLED: "SCAN_CANCELLED",
  TAB_UNAVAILABLE: "TAB_UNAVAILABLE",
  UNSUPPORTED_PAGE: "UNSUPPORTED_PAGE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};

export class AppError extends Error {
  constructor(code, message, details = null) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.details = details;
  }
}

const defaultMessages = {
  [ERROR_CODES.SETUP_REQUIRED]: "SETUP REQUIRED.",
  [ERROR_CODES.API_KEY_MISSING]: "API KEY MISSING. BRUH.",
  [ERROR_CODES.INVALID_PROVIDER_SETTINGS]: "PROVIDER SETTINGS LOOK SUS.",
  [ERROR_CODES.PROVIDER_AUTH_FAILED]: "API KEY GOT REJECTED.",
  [ERROR_CODES.PROVIDER_RATE_LIMITED]: "THE ROBOT IS RATE-LIMITING YOU.",
  [ERROR_CODES.PROVIDER_UNAVAILABLE]: "THE ROBOT SAID NOPE.",
  [ERROR_CODES.PROVIDER_BAD_RESPONSE]: "THE ROBOT SENT GIBBERISH.",
  [ERROR_CODES.DOCUMENT_EMPTY]: "NOT MUCH TO SCAN HERE.",
  [ERROR_CODES.DOCUMENT_TOO_SMALL]: "NOT ENOUGH TEXT TO ANALYZE.",
  [ERROR_CODES.DOCUMENT_TOO_LARGE]: "THIS PAGE IS MASSIVE. TRY AGAIN LATER.",
  [ERROR_CODES.EXTRACTION_FAILED]: "FAILED TO READ PAGE CONTENT.",
  [ERROR_CODES.SCAN_ALREADY_RUNNING]: "SCAN ALREADY RUNNING.",
  [ERROR_CODES.SCAN_CANCELLED]: "SCAN CANCELLED.",
  [ERROR_CODES.TAB_UNAVAILABLE]: "COULD NOT ACCESS TAB.",
  [ERROR_CODES.UNSUPPORTED_PAGE]: "THIS PAGE CANNOT BE SCANNED.",
  [ERROR_CODES.INTERNAL_ERROR]: "INTERNAL EXTENSION ERROR.",
};

export function toAppError(error, fallbackCode = ERROR_CODES.INTERNAL_ERROR) {
  if (error instanceof AppError) {
    return error;
  }

  const code = error?.code || fallbackCode;
  const message = defaultMessages[code] || error?.message || defaultMessages[fallbackCode];
  return new AppError(code, message);
}

export function toUserError(error) {
  const appError = toAppError(error);
  return {
    code: appError.code,
    message: appError.message,
  };
}
